version = 1

[[annotations]]
path = ["**/*.md","**/src/**/*","mvnw*","Jenkinsfile","**/pom.xml","**/*.y*ml",".git*",".mvn/wrapper/maven-wrapper.properties"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["k8s/helm/**/*"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["e2e-js/*.json"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["e2e-python/pyproject.toml","e2e-python/tests/*.py"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["bindings/python/**/*.py","bindings/python/**/*.sh","bindings/python/Dockerfile.build","bindings/python/jar_exclusions.txt","bindings/python/pyproject.toml","bindings/python/setup.py"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["e2e-studio/**/*.ts","e2e-studio/**/*.json"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["package/*.sh","package/*.txt","package/homebrew/*.rb"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["studio/*.json","studio/.npmrc","studio/.nvmrc","studio/scripts/*.js","studio/scripts/*.sh"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["grpc/gRPC-Readme.txt","grpc/gRPC-vs-HTTP-PerformanceTest.txt"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["grpc-client/docs/*.txt"]
SPDX-FileCopyrightText = "Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)"
SPDX-License-Identifier = "Apache-2.0"
